package com.loan_application.loan_application_rules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Applicant implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label(value = "Age")
	private int age;
	@org.kie.api.definition.type.Label(value = "Credit Score")
	private int creditScore;
	@org.kie.api.definition.type.Label(value = "Eligible")
	private java.lang.Boolean eligible;
	@org.kie.api.definition.type.Label(value = "Monthly Income")
	private double monthlyIncome;
	@org.kie.api.definition.type.Label(value = "Yearly Income")
	private long yearlyIncome;

	public Applicant() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public int getAge() {
		return this.age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	public int getCreditScore() {
		return this.creditScore;
	}

	public void setCreditScore(int creditScore) {
		this.creditScore = creditScore;
	}

	public java.lang.Boolean getEligible() {
		return this.eligible;
	}

	public void setEligible(java.lang.Boolean eligible) {
		this.eligible = eligible;
	}

	public double getMonthlyIncome() {
		return this.monthlyIncome;
	}

	public void setMonthlyIncome(double monthlyIncome) {
		this.monthlyIncome = monthlyIncome;
	}

	public long getYearlyIncome() {
		return this.yearlyIncome;
	}

	public void setYearlyIncome(long yearlyIncome) {
		this.yearlyIncome = yearlyIncome;
	}

	public Applicant(java.lang.String name, int age, int creditScore,
			java.lang.Boolean eligible, double monthlyIncome, long yearlyIncome) {
		this.name = name;
		this.age = age;
		this.creditScore = creditScore;
		this.eligible = eligible;
		this.monthlyIncome = monthlyIncome;
		this.yearlyIncome = yearlyIncome;
	}
	
	@Override
	public String toString(){
		return ("Name:"+name+", Age:"+age+", Credit Score:"+creditScore+", Eligible:"+eligible+", Monthly Income:"+monthlyIncome+", Yearly Income:"+yearlyIncome);
	}

}