package com.loan_application.loan_application_rules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Loan implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Amount")
	private long amount;
	@org.kie.api.definition.type.Label(value = "Approved")
	private boolean approved;
	@org.kie.api.definition.type.Label(value = "Comment")
	private java.lang.String comment;
	@org.kie.api.definition.type.Label(value = "Duration")
	private int duration;
	@org.kie.api.definition.type.Label(value = "Interest Rate")
	private double interestRate;
	@org.kie.api.definition.type.Label(value = "Monthly Repayment")
	private double monthlyRepayment;

	public Loan() {
	}

	public long getAmount() {
		return this.amount;
	}

	public void setAmount(long amount) {
		this.amount = amount;
	}

	public boolean isApproved() {
		return this.approved;
	}

	public void setApproved(boolean approved) {
		this.approved = approved;
	}

	public java.lang.String getComment() {
		return this.comment;
	}

	public void setComment(java.lang.String comment) {
		this.comment = comment;
	}

	public int getDuration() {
		return this.duration;
	}

	public void setDuration(int duration) {
		this.duration = duration;
	}

	public double getInterestRate() {
		return this.interestRate;
	}

	public void setInterestRate(double interestRate) {
		this.interestRate = interestRate;
	}

	public double getMonthlyRepayment() {
		return this.monthlyRepayment;
	}

	public void setMonthlyRepayment(double monthlyRepayment) {
		this.monthlyRepayment = monthlyRepayment;
	}

	public Loan(long amount, boolean approved, java.lang.String comment,
			int duration, double interestRate, double monthlyRepayment) {
		this.amount = amount;
		this.approved = approved;
		this.comment = comment;
		this.duration = duration;
		this.interestRate = interestRate;
		this.monthlyRepayment = monthlyRepayment;
	}
	
	@Override
	public String toString(){
	    return ("Amount:"+amount+", Approved:"+approved+", Comment:"+comment+", Duration:"+duration+", Interest Rate:"+interestRate+", Monthly Repayment"+monthlyRepayment);
	}

}